name: tests

on: [push, pull_request]

jobs:
  execute_rspec:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup JRuby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: jruby-9.2.13.0
    - name: Prepare dependencies
      run: |
        bundle config set system 'true'
        bundle install
    - name: Run Test
      env:
        JRUBY_OPTS: "--debug"
      run: |
        bundle exec rspec
